apiVersion: ingress-nodefw.ingress-nodefw/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall-sample
spec:
  interfaces:
  - eth0
  nodeSelector:
    do-node-ingress-firewall: 'true'
  ingress:
  - sourceCIDRs:
       - 172.20.0.0/24
    rules:
    - order: 10
      protocol: icmp
      icmpRule:
        icmpType: 8 #ICMP Echo request
      action: deny
    - order: 20
      protocol: tcp
      protoRule:
        ports: "8000-9000"
      action: deny